spring:
  application:
    name: nsi-couchbase-poc
  couchbase:
      bootstrap-hosts: 10.142.151.101, 10.142.151.102
      env:
        timeouts:
          connect: 10000
          socket-connect: 10000
      bucket:
        name: poc-couchbase
        password: test001
  data:
    couchbase:
      auto-index: true
      repositories:
        enabled: true
server:
  port: 8080